FROM golang:1-alpine

ENV PROJECT_PATH=/service
ENV PATH=$PATH:$PROJECT_PATH/build
ENV CGO_ENABLED=1
ENV GO_EXTRA_BUILD_ARGS="-a -installsuffix cgo"

RUN apk add --no-cache ca-certificates make git bash protobuf protobuf-dev alpine-sdk

RUN mkdir -p $PROJECT_PATH
COPY . $PROJECT_PATH
WORKDIR $PROJECT_PATH
RUN make dev-requirements